import { Component } from '@angular/core';
import {
  AvatarComponent,
  ButtonDirective,
  ButtonGroupComponent,
  CardBodyComponent,
  CardComponent,
  CardFooterComponent,
  CardHeaderComponent,
  ColComponent,
  FormCheckLabelDirective,
  GutterDirective,
  ProgressComponent,
  TableDirective,
  BadgeComponent,
  ButtonModule,
  PageItemDirective,
  PageLinkDirective,
  PaginationComponent,
  ButtonCloseDirective,
  ModalBodyComponent,
  ModalComponent,
  ModalHeaderComponent,
  ModalTitleDirective,
  RowComponent,
  InputGroupComponent,
  DropdownComponent,
  DropdownToggleDirective,
  DropdownItemDirective,
  NavComponent,
  NavItemComponent,
  NavLinkDirective,
} from '@coreui/angular';

@Component({
  selector: 'app-riwayat-transactions-components',
  imports: [
      AvatarComponent,
      ButtonDirective,
      ButtonGroupComponent,
      CardBodyComponent,
      CardComponent,
      CardFooterComponent,
      CardHeaderComponent,
      ColComponent,
      FormCheckLabelDirective,
      GutterDirective,
      ProgressComponent,
      TableDirective,
      BadgeComponent,
      ButtonModule,
      PageItemDirective,
      PageLinkDirective,
      PaginationComponent,
      ButtonCloseDirective,
      ModalBodyComponent,
      ModalComponent,
      ModalHeaderComponent,
      ModalTitleDirective,
      RowComponent,
      InputGroupComponent,
      DropdownComponent,
      DropdownToggleDirective,
      DropdownItemDirective,
      NavComponent,
      NavItemComponent,
      NavLinkDirective,
  ],
  standalone : true,
  templateUrl: './riwayat-transactions-components.component.html',
  styleUrl: './riwayat-transactions-components.component.scss',
})
export class RiwayatTransactionsComponentsComponent {
  kasirName = 'Ahmad Budi Utomo';
  transactionDate = '22/10/2025';
  branchName = 'Chickroll Yogyakarta';

}
